### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by G3ph4z** [JJ-8/CTFNote#60]
Hello, 

I've installed the latest version, configured the discord bot, but when I imported an event from CTFTime, this happened:
```
Bot name bot is online
Failed to get CTF from the database: TypeError: Cannot read properties of undefined (reading 'id')
    at buildCtf (/app/dist/discord/database/ctfs.js:43:17)
    at /app/dist/discord/database/ctfs.js:139:43
    at step (/app/dist/discord/database/ctfs.js:33:23)
    at Object.next (/app/dist/discord/database/ctfs.js:14:53)
    at fulfilled (/app/dist/discord/database/ctfs.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by G3ph4z** [comment]
Also got this when tried to create a task and assigned it to myself:


```
Could not find a non-full category for new task {
  id: 5,
  ctf_id: 6,
  title: 'teszt',
  description: '',
  tags: undefined,
  flag: ''
} true
Task channel not found {
  id: 5,
  ctf_id: 6,
  title: 'teszt',
  description: '',
  tags: undefined,
  flag: ''
} {
  id: 6,
  title: 'Teszt event',
  weight: 0,
  ctf_url: null,
  logo_url: null,
  ctftime_url: null,
  description: '',
  start_time: 2023-07-19T03:21:00.000Z,
  end_time: 2023-07-20T03:55:00.000Z,
  secrets_id: 6
} 0
Task channel not found {
  id: 5,
  ctf_id: 6,
  title: 'teszt',
  description: '',
  tags: undefined,
  flag: ''
} {
  id: 6,
  title: 'Teszt event',
  weight: 0,
  ctf_url: null,
  logo_url: null,
  ctftime_url: null,
  description: '',
  start_time: 2023-07-19T03:21:00.000Z,
  end_time: 2023-07-20T03:55:00.000Z,
  secrets_id: 6
} 0

```

**Comment by G3ph4z** [comment]
So I figured out that it was a user error by me, I thought the bot will automatically create the needed channels for the event. 

Anyway, thanks!

**Comment by JJ-8** [comment]
@G3ph4z, thank you for your feedback. Since other users are now also using my fork, I have improved the documentation in the README.

**Comment by G3ph4z** [comment]
@JJ-8 I'm a bit late, but thank you so much for your work, it's very helpful!
